### ISSUE TITLE
Include API name directly called by applications in the error messages.

### ISSUE THREAD

**Issue by negiyas** [IBM/zDNN#17]
**Is your feature request related to a problem? Please describe.**
- Messages shown when zDNN APIs returns errors are not clear. The corresponding APIs directly called by applications are not shown in the messages. Accordingly application programmers can know which API causes errors.
- ZDNN_ELEMENT_RANGE_VIOLATION is unclear a little bit, either index range violation or value range violation. 

**Describe the solution or source you'd like**
Please include API name directly called by applications (e.g. zdnn_log, zdnn_softmax) in the error message.

**Additional context**
The followings are possible samples to add API names in the error messages.
ERROR: **zdnn_log:** aiu_ops_func_specific() (aiu_ops.c:155): ZDNN_ELEMENT_RANGE_VIOLATION: Range violation on tensor data
ERROR: **zdnn_transform_origtensor:** dnn_handle_fp_errors() (stickify.c:328): ZDNN_CONVERT_FAILURE: Some tensor elements too large. Consider model tuning.
ERROR: **zdnn_transform_origtensor:** zdnn_transform_origtensor() (stickify.c:1735): transform_origtensor_smalldim1() (ZDNN_NHWC) failed, status = 00100003 (ZDNN_CONVERT_FAILURE: Floating point data conversion failure.)

**Comment by n-marion** [comment]
This is not something we'll be doing.
