### ISSUE TITLE
Release 1.1.0

### ISSUE THREAD

**Issue by ngueorguiev** [IBM/zDNN#21]
### Current Observation:

The latest code is 1.1.0, but the latest released release is 1.0.1. What needs to be done to have the 1.1.0?

**Comment by ngueorguiev** [comment]
@n-marion @Andreas-Krebbel fyi

**Comment by n-marion** [comment]
Hello @ngueorguiev ,

The main branch is bumped to v1.1.0 but that is intended for a future release. Currently there are no enhancements to zDNN within the main branch to warrant a new release at this time.

**Comment by n-marion** [comment]
Hello @ngueorguiev ,

v1.1.0 has officially been released.
